### ISSUE TITLE
The fancy-chat isn't loading, instead sending an error message

### ISSUE THREAD

**Issue by ShpongledKane** [BeeStation/BeeStation-Hornet#8021] opened 2022-11-05 20:39 UTC
Issue reported from  Round ID: 41198 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1583

The same applies to some of the popping windows, such as PDA or consoles interfaces, making the game unplayable. Everything works just fine on sage, so I only got this issue with acacia just recently. The OS is Windows 7, and my IE client is updated to 11-th version, I also tried reinstalling byond and clearing cache, which didn't help.

![изображение](https://user-images.githubusercontent.com/58078693/200140428-97c033d8-88cc-4c82-975c-0f6e17db4bf2.png)

**Comment by itsmeow** [comment] 2022-11-05 20:43
can you paste the error message text so I can translate it?

**Comment by ShpongledKane** [comment] 2022-11-05 20:44
Объект не поддерживает свойство или метод "subscribe"
   at http://127.0.0.1:61767/tmp2732/tgui.bundle.js:1:1142411
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0E; .NET4.0C)
State: {}

**Comment by itsmeow** [comment] 2022-11-05 20:46
`Object does not support property or method "subscribe"`

**Comment by itsmeow** [comment] 2022-11-05 20:48
Can you try clearing your BYOND Cache?
Byond -> Ctrl+P -> Games
![image](https://user-images.githubusercontent.com/10366817/200140726-f4173ef1-2e6d-4081-be3d-eefb9c386df3.png)

**Comment by ShpongledKane** [comment] 2022-11-05 20:54
I tried it, the error stays the same.

**Comment by itsmeow** [comment] 2022-11-05 21:02
Hmmm, if you know how, you can actually spin up a local tgui-dev server, log into Acacia, then hit F5 on the panel so it reloads and connects to the dev server. That should give the unobfuscated error output in the dev console, that way I can investigate further.
The dev server is in the repo at `bin/tgui-dev.cmd` if you clone it locally.

**Comment by ShpongledKane** [comment] 2022-11-05 21:09
I can try even though I have no idea how to do that.

**Comment by ShpongledKane** [comment] 2022-11-05 21:22
Okay, I did manage to run the server, but how do I "log into Acacia"?

**Comment by itsmeow** [comment] 2022-11-05 21:44
Just open BYOND and connect as usual

**Comment by ShpongledKane** [comment] 2022-11-05 22:07
Sorry, maybe I misunderstood something, but pressing F5 does nothing on Acacia.

**Comment by itsmeow** [comment] 2022-11-05 22:22
So I was able to reproduce this myself by joining. Thanks for trying!

**Comment by itsmeow** [comment] 2022-11-05 22:27
```
  21.196 store FatalError: TypeError: Object doesn't support property or method 'subscribe'
  at setupApp (./tgui-workspace/packages/tgui-panel/index.js:78)
```

Seems to be a deployment issue. We are resolving it now

**Comment by ShpongledKane** [comment] 2022-11-05 22:28
Alright, thanks for helping!

**Comment by Crossedfall** [comment] 2022-11-05 22:30
Resolved! Thanks for the report.

**Closed as completed by Crossedfall** 2022-11-05 22:30 UTC
