### ISSUE TITLE
[Bug]: The RCD upgrades are all fucked up

### ISSUE THREAD

**Issue by Geatish** [BeeStation/BeeStation-Hornet#11438] opened 2024-09-06 21:14 UTC
### BYOND Version

515.1643

### Round Date

2024/09/06

### Round ID

49897

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 1b8f225789](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#11279: 'Client-side Jukebox, Client-side Lobby Music, Synchronised Music & TGUI Panel Music Player Improvements' by PowerfulBacon at commit 983d5accc4](https://www.github.com/beestation/beestation-hornet/pull/11279)

### Describe the bug

The RCD upgrades give the wrong upgrade(s) and in some case no upgrade at all.
Only the silo link and furniture works, but you also get the silo link on the in the furniture upgrade????

Also that the individual disks are hard to tell apart, since only their description is different. 

### What did you expect?

I expected the upgrades to give me what it said they would give me

### Reproducible steps

1. get a rcd
2. get the upgrades
3. try out the upgrades and see that they all give the wrong thing or nothing at all

**Comment by aramix273** [comment] 2024-09-07 11:23
duplicate of #11369 
potentially solved by #11425

**Comment by HowToLoLu** [comment] 2024-09-10 22:47
Confirmed fixed, can be closed

**Closed as completed** 2024-09-11 07:12 UTC
