### ISSUE TITLE
[Bug]: ERT Hardsuit Flashlight Doesn't Work

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11646] opened 2024-10-05 22:19 UTC
### Round ID

50220

### Describe the bug

Spawned in as an ERT, couldn't turn on the hardsuit flashlight with the helmet on.

### What did you expect?

For it to work.

**Comment by Tsar-Salat** [comment] 2024-10-05 22:31
duplicate of #10526 

Guess I didnt fix it

**Closed as completed** 2024-10-19 13:21 UTC
