### ISSUE TITLE
Beeshop Items and Latejoin Assistants

### ISSUE THREAD

**Issue by FortSumter** [BeeStation/BeeStation-Hornet#2283] opened 2020-08-11 18:38 UTC
Issue reported from  Round ID: 19734 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1527

Items purchased in the Beeshop do not spawn on late-join assistants 90% of the time for unexplained reasons. Works properly for any other job type I've played.

**Comment by Crossedfall** [comment] 2020-08-12 16:13
It's fairly inconsistent, but I was able to reproduce this issue within my dev environment. Although, I can't determine exactly what causes it. Of the 10 times I spawned in, it only happened once.

Steps taken to reproduce:

1. Grant myself 999999 metacoins
2. Purchase the hat
3. Late join as an assistant
4. If I had the hat, I'd delete my mob and send the ghost back to the lobby
5. Repeat steps 3 and 4 until the issue presented itself

 An added quirk I noticed was that it seems as though you can only spawn in with items in your hand once. While I don't expect this to be a regular issue, if you get sent back to lobby and re-join you wont have the outfit you have equipped from the Beeshop.

Assigning to @ike709 since the shop is his domain

**Comment by ike709** [comment] 2020-08-12 17:10
🤔

**Comment by Crossedfall** [comment] 2020-08-12 22:14
From #2194 

> Bee coin shop items (exec jacket, tie, glassess, lace up shoes) I have purchased and equip often fail to apply when I late join. If I join right after round start im usually fine, past 5 minutes I seem to have a nearly 100% chance of not spawning in with any of the items.
>
> Really all I can say at this point :<

**Comment by eLeCtrOssSnake** [comment] 2020-10-07 15:40
I can confirm that sometimes, mainly as assistant cuz I play a lot of assistant I do not get my fancy items even though I am not late joining. It's kinda weird, but it does happen a lot.

**Comment by FortSumter** [comment] 2020-10-07 23:44
How has this not been resolved? I brought this up months ago and even Crossed commented on the problem.

**Closed as completed** 2022-06-06 18:54 UTC
Labels: Bug, Triaged
