### ISSUE TITLE
Spacepol cannot access their own shuttle consoles

### ISSUE THREAD

**Issue by LodedDiper69** [BeeStation/BeeStation-Hornet#8613] opened 2023-03-04 18:15 UTC
## Round ID & Round Date:

I don't quite remember the ID, but I'm pretty sure it was before 42990. The date is 03-04-2023.

## Testmerges:

Almost certainly caused by #8233 .

## Reproduction:

Step 1: Spawn as a space cop
Step 2: Attempt to access your own console
Step 3: 
![image](https://user-images.githubusercontent.com/101019561/222922191-f8ef78f4-4592-4c90-b5d1-77ab8203215b.png)

**Comment by itsmeow** [comment] 2023-03-05 01:47
Fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/8395

**Comment by itsmeow** [comment] 2023-03-05 01:49
Oh. It's a supercruise TM issue. Please direct this to the PR, not the general GitHub if you are confident it was caused by a testmerge.

**Closed as not planned by itsmeow** 2023-03-05 01:49 UTC
