### ISSUE TITLE
Cave generation is broken

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#5180] opened 2021-08-23 17:12 UTC
Related to https://github.com/BeeStation/BeeStation-Hornet/pull/4800

Tendrils spawn in things like the golem ship and pod people terrarium, and goliaths spawn in 1x1 areas.

**Comment by ike709** [comment] 2021-08-23 17:14
eeeeeeeee @KubeRoot

**Comment by KubeRoot** [comment] 2021-08-23 17:26
Oh right :weary:
I forgot to look more deeply into this, I didn't find a fix for the issue on tg (implying it probably doesn't happen there), will need to investigate myself

**Comment by KubeRoot** [comment] 2021-08-23 18:58
I figured out tendrils spawning in ruins, not sure what's up with goliaths spawning in 1x1 areas - I'm not even sure if I understand correctly, but going through every goliath in existence on a local server twice didn't show any. Could you elaborate on what the issue is, and if it's even a bug?

**Comment by williamcll** [comment] 2021-08-25 03:18
should be fixed now right?

**Comment by KubeRoot** [comment] 2021-08-25 14:10
> should be fixed now right?

Nothing was done to address the "goliaths spawn in 1x1 areas" part AFAIK.

**Closed as completed** 2021-08-25 14:52 UTC
