### ISSUE TITLE
Transcripts that are more than 1 page long cause clients to freeze

### ISSUE THREAD

**Issue by Haliris** [BeeStation/BeeStation-Hornet#9125] opened 2023-05-30 21:37 UTC
Issue reported from  Round ID: 44267 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Steps:

Record a very long conversation with the universal recorder, to have a lot of lines.

Print the transcript and try to open it, BYOND will stop responding.

I can provide runtime if needed.

**Comment by JixS4v** [comment] 2023-05-30 21:41
Probably an overflow or something from printing it on a single page.

**Comment by HowToLoLu** [comment] 2023-05-31 01:24
> Probably an overflow or something from printing it on a single page.

Seems like that's the case- tapes store up to 600 messages, and even 97 on a paper overwhelms the game to run at 15 seconds a tick.

I'll work on a fix that splits the transcript into multiple pages (which should also help readability for such long recordings)

**Comment by HowToLoLu** [comment] 2023-05-31 03:56
Alright, final update- apparently the HTML renderer in game does _not_ like many root elements (or root text for that matter)

Fix'll be PR'ed soon.

**Comment by itsmeow** [comment] 2023-05-31 06:04
Duplicate of #9058

**Closed as completed by itsmeow** 2023-05-31 06:04 UTC
