### ISSUE TITLE
When I try to write on paper I'm getting this error, it makes paperwork impossible for me.

### ISSUE THREAD

**Issue by Leshens** [BeeStation/BeeStation-Hornet#6241] opened 2022-01-24 09:13 UTC
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Object expected.
   at Anonymous function (http://127.0.0.1:64040/tmp10740/tgui.bundle.js:1:432868)
   at n.createPreview (http://127.0.0.1:64040/tmp10740/tgui.bundle.js:1:432854)
   at Anonymous function (http://127.0.0.1:64040/tmp10740/tgui.bundle.js:1:434185)
   at He (http://127.0.0.1:64040/tmp10740/tgui-common.bundle.js:1:181286)
   at Ge.prototype.setState (http://127.0.0.1:64040/tmp10740/tgui-common.bundle.js:1:182305)
   at n.onInputHandler (http://127.0.0.1:64040/tmp10740/tgui.bundle.js:1:434159)
   at o.handleOnInput (http://127.0.0.1:64040/tmp10740/tgui-common.bundle.js:1:347540)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"leshens","interface":"PaperSheet","window":{"key":"[0x2024820]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-2559

**Comment by ike709** [comment] 2022-01-24 09:19
Dupe of #6205

**Closed as completed by ike709** 2022-01-24 09:19 UTC
