### ISSUE TITLE
Contractor uplink breaks if one of the targets cryos.

### ISSUE THREAD

**Issue by KittyNoodle** [BeeStation/BeeStation-Hornet#4643] opened 2021-06-25 00:47 UTC
Issue reported from  Round ID: 30787 (BeeStation Sage - Roleplay)

Reporting client version: 514.1556

**Comment by Sinestia** [comment] 2021-06-25 04:46
duplicate of like all of these

https://github.com/BeeStation/BeeStation-Hornet/issues?q=is%3Aissue+is%3Aopen+contractor

**Comment by KittyNoodle** [comment] 2021-06-26 21:50
and it still has not been fixed.

**Comment by MNarath1** [comment] 2021-07-01 17:30
I looked into this once and the problem is that currently the cryo objective handler proc thats supposed to handle cryo of targets etc isn't working for contractor as the antag is defined differently from pretty much all of them in short it can'
t handle the contractor objective so if the tablet tries to find the persons in its target list and gets null for one of them it runtimes and breaks.

**Comment by MNarath1** [comment] 2021-07-01 17:31
the fact that contractor code is kinda a mess and hard to read definitly does not help with making a fix for this.

**Closed as completed** 2021-07-05 10:08 UTC
