### ISSUE TITLE
Unable to construct doors in door slots with RCD

### ISSUE THREAD

**Issue by JikkaJoestar** [BeeStation/BeeStation-Hornet#10459] opened 2024-01-11 23:47 UTC
Issue reported from  Round ID: 47308 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Unable to construct a door in a door slot with an RCD. Unsure if this is intended.

**Comment by Tsar-Salat** [comment] 2024-01-11 23:54
Record the reproduction steps please.

I currently cannot reproduce this with minimal information.


https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/1dcbe163-f662-4ab4-9e5f-a1efaa4f3471


![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/6a05920f-bcfe-404c-ad88-d56e6143f457)

**Comment by Miliviu** [comment] 2024-01-12 07:23
I can reproduce the issue, firstly, get an emag, then emag a door, after that try to replace that door with the RCD, even if you remove the door you will not be able to put a door there

https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/5ea5c633-b170-4d00-9453-b96695a84522

**Comment by Miliviu** [comment] 2024-01-12 07:42
After some testing and switching commits, I've discovered that this issue #8195 was merged

**Closed as completed** 2024-01-24 22:26 UTC
