### ISSUE TITLE
a big lag issue at a round (xenoarch issue?)

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7259] opened 2022-07-12 19:50 UTC
## Round ID:
39239 

## Testmerges:
xenoarchaenology

## Reproduction:
just suspect.
It appeared Xenoarch made some lag that made SSticker slower a bit for a certain period. need to runtime check or loop.

**Comment by DrDuckedGoose** [comment] 2022-07-12 19:59
May have been caused by ``"SSORBITS: Created a new dynamic free level # as none were available at the time."``
Addressed in https://github.com/BeeStation/BeeStation-Hornet/pull/6718/commits/6fa291f6375199470e9e906fd8821bba41ab4a1f.

However, I'd hold off closing until Bacon confirms.

**Comment by DrDuckedGoose** [comment] 2022-07-15 07:35
This is my first clue.
![image](https://user-images.githubusercontent.com/40559528/179175333-e11b98d1-921e-472f-b9bb-25ab6307b0c9.png)

**Closed as completed** 2022-07-23 17:20 UTC
