### ISSUE TITLE
Airlock painter doesn't have a sprite when empty?

### ISSUE THREAD

**Issue by Coding-Grape** [BeeStation/BeeStation-Hornet#7976] opened 2022-10-29 02:56 UTC
## Testmerges:
[#7826: 'Pumpkinpeople - A Halloween special' by DrDuckedGoose at commit fcd6ed1584](https://www.github.com/beestation/beestation-hornet/pull/7826)
[#7659: 'Removes some major sleepers (100% lag free)' by PowerfulBacon at commit 95bedebb38](https://www.github.com/beestation/beestation-hornet/pull/7659)

## Reproduction:
use an airlock painter completely
it no longer has a sprite

picture (there is an airlock painter in my hand)
![image](https://user-images.githubusercontent.com/95245106/198782336-01cf6929-c294-491a-9d12-c2dbd390e256.png)

**Comment by itsmeow** [comment] 2022-10-29 03:24
Duplicate of #7915

**Closed as not planned by itsmeow** 2022-10-29 03:24 UTC
