### ISSUE TITLE
Slime jelly autoinjectors from industrial green extracts reset blood level instead of increasing it

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#2280] opened 2020-08-11 03:00 UTC
Issue reported from  Round ID: 19713 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1528

Test merges: none

Reproduction: become a slimeperson and increase your "blood" (read: slime jelly) level over 100%. Then, use a slime jelly bubble in yourself. It will not add 50u of slime jelly and increase your blood level, it will bring it back down to 100%.

**Comment by Crossedfall** [comment] 2020-08-12 17:49
Issue caused by the IPC port from Oracle https://github.com/BeeStation/BeeStation-Hornet/pull/463

Problem datum is:

https://github.com/BeeStation/BeeStation-Hornet/blob/b0bc1eb6282c1247ac343d8fc18f6f414423e93e/code/modules/mob/living/carbon/human/species.dm#L1045-L1050

Whenever the reagent is processed by the above, it resets the blood level to the "normal" value.

Could be resolved by either adding a check to see if the species is meant to have excess blood, or this proc could be reworked in its entirety.

**Closed as completed** 2022-06-06 18:53 UTC
Labels: Bug, Good first issue, Triaged, Hacktoberfest
