### ISSUE TITLE
Invisible mobs can't see speech

### ISSUE THREAD

**Issue by Tyranicranger4** [BeeStation/BeeStation-Hornet#7220] opened 2022-07-07 14:30 UTC
## Reproduction:
Any mob with their invisibility variable above 0 cannot see speech. This includes revenants. Bacon says it's probably related to #6587

**Comment by itsmeow** [comment] 2022-07-10 09:23
Duplicate of #7053

**Closed as completed** 2022-07-16 07:56 UTC
Labels: Triaged, p-Priority: High
