### ISSUE TITLE
GPS unit direction arrows always point north.

### ISSUE THREAD

**Issue by Oscari-pog** [BeeStation/BeeStation-Hornet#6255] opened 2022-01-26 13:19 UTC
## Testmerges:

The following pull requests are currently test merged:
#5755: 'Updates Kilo Station and re-adds it to rotation' by dog132-ss13 at commit de60237356
#6247: 'TGUI maintenance chores and juke upgrades' by Crossedfall at commit 375ab808ea
#6253: 'Bulk VSCode & Unit Testing Improvements' by ike709 at commit 2f5c65e03e
## Reproduction:

1. Grab a GPS
2. Open it
3. Oh no
![likethis](https://user-images.githubusercontent.com/70425197/151169952-1c67bd9e-89b2-4e1b-b5f1-eb515fcd5765.PNG)

**Comment by Crossedfall** [comment] 2022-01-26 16:52
Issue confirmed to be caused by #6247

**Comment by KubeRoot** [comment] 2022-01-26 17:05
PR has been updated to fix the issue, should be fixed when the testmerge is updated.

**Closed as completed by KubeRoot** 2022-01-26 17:05 UTC
Labels: Triaged
